app/fast/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, BooleanField, SubmitField, IntegerField,PasswordField, RadioField
from flask_wtf.file import FileField
from wtforms.fields.html5 import DateField
from wtforms.validators import Optional, Length, Required, URL, Email, EqualTo
from flask.ext.pagedown.fields import PageDownField

class ProfileForm(Form):
    firstName=StringField('First Name', validators=[Required(),Length(1,30)])
    lastName=StringField('Last Name', validators=[Required(), Length(1,30)])
    submit=SubmitField('Submit')
class RegisterForm(Form):
    firstName=StringField('First Name', validators=[Required(),Length(1,30)] )
    lastName=StringField('Last Name', validators=[Required(),Length(1,30)] )
    country=StringField('Country', validators=[Required(),Length(1,30)] )
    city=StringField('City', validators=[Required(),Length(1,30)] )
    phoneNumber=IntegerField('Phone Number', validators=[Required()])
    username=StringField('Nick Name', validators=[Required()])
    email = StringField('Email', validators=[Required(), Length(1, 64),
                                             Email()])

    password = PasswordField('Password', [Required(), EqualTo('confirm')])
    confirm  = PasswordField('Confirm')
    submit = SubmitField('Register')

class CreatLeagueForm(Form):
    leagueName=StringField('League Name', validators=[Required(), Length(3,30)])
    photo_league = FileField('Picture upload')
    private = RadioField('private', choices=[('private','private'),('public','public')])
    gameType = RadioField('Game Type', choices=[('Seasonal','Seasonal'),('Keeper','Keeper')])
    matchType = RadioField('Match Type', choices=[('Classic Mode  (Rotisserie)','Classic Mode  (Rotisserie)'),('Head-to-head','Head-to-head')])
    champion = RadioField('Champion', choices=[('Play-offs','Play-offs'),('Head-to-head','Head-to-head')])
    submit=SubmitField('Create a League')

app/fast/__init__.py
from flask import Blueprint

fast=Blueprint('fast', __name__)
from . import routes

app/fast/routes.py
from flask import render_template, flash, redirect, \
    url_for, abort, request, current_app
from flask.ext.login import login_required, current_user
from ..import db
from ..models import User, PersonalInfo,League
from . import fast
from .forms import ProfileForm, RegisterForm, CreatLeagueForm
from config import Config
from flask.ext.sqlalchemy import Pagination
import sqlalchemy
from flask.ext.login import login_required, current_user
from sqlalchemy.exc import IntegrityError, InvalidRequestError
from sqlalchemy import exc
from tools import s3_upload





@fast.route("/", defaults={"page": 1})
@fast.route("/")
def index():
    form = RegisterForm()
    if current_user.is_authenticated:
        user_id=current_user.id
        result= League.query.join(User.league_tag).filter(User.id == user_id).first()
        return render_template ("fast/index.html", form=form, result=result)
    else:
        return render_template ("fast/index.html", form=form)
@fast.route("/user/<username>")
def user(username):
    """initializing presonalinfo for the current user"""
    user = User.query.get(current_user.id)
    personal = PersonalInfo.query.\
        filter(PersonalInfo.user_id == current_user.id).first()
    if personal is None:
        #userinfo = PersonalInfo(first_name='***', last_name='***')
        #db.session.add(userinfo)
        #db.session.commit()
        #flash("Please update your profile")
        return redirect(url_for("fast.profile"))
    return render_template('fast/user.html', user=user, personal=personal)

@fast.route("/Register", methods=["GET", "POST"])
def Register():
    """Register a new user."""
    form = RegisterForm()
    try:
        if request.method == "POST" and form.validate_on_submit():

            firstname=form.firstName.data
            lastname=form.lastName.data
            country=form.country.data
            city=form.city.data
            phonenumber=form.phoneNumber.data
            info=PersonalInfo(first_name=firstname, last_name=lastname, country=country, city=city, phonenumber=phonenumber)
            db.session.add(info)
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = User\
            (email=email, username=username, is_admin=False, password=password)
            db.session.add(user)
            db.session.commit()
            flash("User {0} was registered successfully.".format(username))
            return redirect(url_for("auth.login"))
    except (IntegrityError,InvalidRequestError) as e:
        db.session.rollback()
        flash('Sorry! User is already exists!')


    return render_template("fast/Register.html", form=form)
@fast.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = RegisterForm()
    if form.validate_on_submit():
        current_user.user_info.first_name = form.firstName.data
        current_user.user_info.last_name = form.lastName.data
        current_user.user_info.age = form.Age.data
        current_user.user_info.location = form.location.data
        current_user.user_info.bio = form.bio.data
        current_user.user_info.user_id = current_user.id
        db.session.add(current_user.user_info)
        db.session.commit()
        flash("You have been updated your profile")
        return redirect(url_for('fast.user', username=current_user.username))
    if current_user.user_info:
        form.firstName.data = current_user.user_info.first_name
        form.lastName.data = current_user.user_info.last_name
        form.location.data = current_user.user_info.location
        form.Age.data = current_user.user_info.age
        form.bio.data = current_user.user_info.bio
    return render_template('fast/profile.html', form=form)

@fast.route('/team')
def team():
    return render_template('fast/team.html')

@fast.route('/CreateLeague', methods=['GET', 'POST'])
@login_required
def  CreateLeague():
    form=CreatLeagueForm()

    if current_user.is_authenticated:
        try:
            if form.validate_on_submit():
                output = s3_upload(form.photo_league)
                photo="https://s3-us-west-2.amazonaws.com/upload-picture/upload-picture.s3-website-us-west-2.amazonaws.com/"+output
                leagueName=form.leagueName.data
                game_type=form.gameType.data
                league_type=form.private.data
                champion=form.champion.data
                match_type=form.matchType.data
                user_id=current_user.id
                create=League(league_name=leagueName, number_of_team=1,  league_type= league_type, game_type=game_type, match_type=match_type, champion=champion, url=photo, user_id=user_id)
                db.session.add(create)
                db.session.commit()
                flash('Congratulation! You have created {0} League successfully!'.format(leagueName))
                return redirect(url_for('fast.Confirmation'))
        except (IntegrityError,InvalidRequestError) as e:
            db.session.rollback()
            flash('Sorry! The give data already exists. Try again!')
    else:
        flash('Please Logiffffn!')
        return redirect(url_for('auth.login'))
    return render_template('fast/create-league.html', form=form)
@fast.route('/Confirmation')
@login_required
def Confirmation():

    result=League.query.filter(League.user_id==current_user.id).first()

    return render_template('fast/confirmation.html', result=result)

@fast.route('/EditLeague' , methods=['GET', 'POST'])
@login_required
def  EditLeague():
    form=CreatLeagueForm()
    user_id=current_user.id
    user_info= League.query.join(User.league_tag).filter(User.id == user_id).first()
    if form.validate_on_submit():
        output = s3_upload(form.photo_league)
        photo="https://s3-us-west-2.amazonaws.com/upload-picture/upload-picture.s3-website-us-west-2.amazonaws.com/"+output
        user_info.league_name= form.leagueName.data

        if  "." in photo and photo.rsplit('.', 1)[1] in current_app.config["ALLOWED_EXTENSIONS"]:
            user_info.url = photo
        else:
            user_info.url = user_info.url

        user_info.league_type = form.private.data
        user_info.game_type = form.gameType.data
        user_info.match_type = form.matchType.data
        user_info.champion = form.champion.data
        user_info.user_id=current_user.id
        db.session.add(user_info)
        db.session.commit()
        flash('League information updated!')
        return redirect(url_for('fast.LeagueInfo'))


    if user_info:
        form.leagueName.data=user_info.league_name
        form.photo_league.data=user_info.url
        form.private.data = user_info.league_type
        form.gameType.data = user_info.game_type
        form.matchType.data = user_info.match_type
        form.champion.data = user_info.champion

    return render_template('fast/edit-league.html', form=form, user_info=user_info)


@fast.route('/LeagueInfo')
@login_required
def  LeagueInfo():
    user_id=current_user.id
    result= League.query.join(User.league_tag).filter(User.id == user_id).first()

    return render_template("fast/league-info.html", result=result)





@fast.route('/results')
def results():
    return render_template('fast/results.html')
@fast.route('/forum')
def forum():
    return render_template('fast/forum.html')

app/templates/fast/Register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<div class="row">
  <div class="col-lg-2 col-md-2 col-sm-12">
  </div>
  <div class="col-lg-8 col-md-8 col-sm-12">
    <div class="panel panel-default">
    <div class="panel-heading">
      Registration
    </div>
    <div class="panel-body">
    {{ wtf.quick_form(form) }}
    </div>
  </div>
  </div>
  <div class="col-lg-2 col-md-2 col-sm-12">
  </div>
</div>

  {% endblock %}

app/templates/fast/confirmation.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<div class="container">
  <legend>Confirmation</legend>
  <h3>Leage Created:</h3>
  <div class="row">

    <div class="col-lg-4 col-md-4 col-sm-12">

  <img class="img-rounded" alt="Cinque Terre" width="304" height="236"
 src="{{result.url}}"></img>
 </div>
 <div "col-lg-4 col-md-4 col-sm-12">
   <p>Leage Name : {{result.league_name}}</p>
    <p>Number of Team : {{result.number_of_team}}</p>
     <p>League Type: {{result.league_type}}</p>
      <p>Game Type : {{result.game_type}}</p>
        <p>Match Type : {{result.match_type}}</p>
       <button class="btn btn-lg btn-success">Edit</button>

 </div>
 </div>
</div>

{% endblock %}

app/templates/fast/create-league.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<!DOCTYPE html>
<HEAD>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</HEAD>
<div class="space">
<div class="container">
  <form class="form-horizontal" action="{{url_for('fast.CreateLeague')}}"  enctype="multipart/form-data" method="post" >
                    {{ form.hidden_tag() }}
                  {{ wtf.form_errors(form, hiddens="only") }}
                  <fieldset>
                          <legend class="text-center header">Create a League</legend>
  <div class="form-group">
    <div class="col-lg-4 col-md-4 col-sm-12">
    {{ wtf.form_field(form.leagueName) }}
  </div>
  </div>

  <div class="form-group">
    <h5><strong>Photo/Symbol of the league</strong></h5>


        {{ wtf.form_field(form.photo_league) }}

  </div>

  <div class="form-group">
    <h5><strong>Private or Public(anybody can join)</strong></h5>
    {{ wtf.form_field(form.private) }}
  </div>

  <div class="form-group">
      <h5><strong>Game Type</strong></h5>
    {{ wtf.form_field(form.gameType) }}
  </div>
  <div class="form-group">
      <h5><strong>Match Type</strong></h5>
    {{ wtf.form_field(form.matchType) }}
  </div>
  <div class="form-group">
      <h5><strong>Champion</strong></h5>
    {{ wtf.form_field(form.champion) }}
  </div>
  <div class="form-group">
    {{ wtf.form_field(form.submit) }}
  </div>


</fieldset>
</form>
</div>
</div>
{% endblock %}

app/templates/fast/edit-league.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<!DOCTYPE html>
<HEAD>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</HEAD>
<div class="space">
<div class="container ">
  <div class="row well">
    <div class="col-lg-8 col-md-8 col-sm-12 col-md-offset-2 col-lg-offset-2 col-sm-offset-2">
  <form class="form-horizontal" action="{{url_for('fast.EditLeague')}}"  enctype="multipart/form-data" method="post" >
                    {{ form.hidden_tag() }}
                  {{ wtf.form_errors(form, hiddens="only") }}
                  <fieldset>
                          <legend class="text-center header">Edit a League</legend>
  <div class="form-group">
    <div class="col-lg-4 col-md-4 col-sm-12">
    {{ wtf.form_field(form.leagueName) }}
  </div>
  </div>

  <div class="form-group">
    <h5><strong>Photo/Symbol of the league</strong></h5>

    <img class="img-rounded" alt="Cinque Terre" width="304" height="236"
   src="{{user_info.url}}"></img>
        {{ wtf.form_field(form.photo_league) }}

  </div>

  <div class="form-group">
    <h5><strong>Private or Public(anybody can join)</strong></h5>
    {{ wtf.form_field(form.private) }}
  </div>

  <div class="form-group">
      <h5><strong>Game Type</strong></h5>
    {{ wtf.form_field(form.gameType) }}
  </div>
  <div class="form-group">
      <h5><strong>Match Type</strong></h5>
    {{ wtf.form_field(form.matchType) }}
  </div>
  <div class="form-group">
      <h5><strong>Champion</strong></h5>
    {{ wtf.form_field(form.champion) }}
  </div>
  <div class="form-group">
     <button type="submit" class="btn btn-lg btn-success" >Submit</button>
  </div>


</fieldset>
</form>
</div>
</div>
</div>
{% endblock %}

app/templates/fast/footer.html
{% block footer %}
<!--------------------------------- Fixed footer ----------------------------->
    <div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
    	<div class="container">
			<div class="navbar-text pull-left">
    			<p>© 2016 SUBOTAI.</p>
			</div>
			<div class="navbar-text pull-right">
					<a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
					<a href="#"><i class="fa fa-twitter fa-2x"></i></a>
					<a href="#"><i class="fa fa-google-plus fa-2x"></i></a>
			</div>
		</div>
  </div>
<!---------------------------Fixed Footer end here---------------------------->
{% endblock%}

app/templates/fast/forum.html
{% extends "base.html" %}
{% block page_content %}
<div class="space">
<h1>The page is under construction</h1>
</div>
{% endblock %}

app/templates/fast/index.html
{% extends "base.html" %}
{% block page_content %}

{% if current_user.is_authenticated %}
 <div class="container">
    {% if  not result %}


          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-lg-offset-6 col-md-offset-6 col-sm-offset-2">
            <div class="jumbotron">
              <h1>Fantansy Game</h1>
            <a class="btn btn-success btn-lg span7"  href="{{url_for('fast.CreateLeague')}}">Create League</a>

            <button class="btn btn-success btn-lg span7">Join League</button>
          </div>

          </div>
          <div>

           </div>

         </div>
         {% else %}
         <div class="container well">
           <legend>League Info</legend>

           <div class="row">

             <div class="col-lg-4 col-md-4 col-sm-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">

           <img class="img-rounded" alt="Cinque Terre" width="304" height="236"
          src="{{result.url}}"></img>
          </div>
          <div "col-lg-4 col-md-4 col-sm-12">
            <p>Leage Name : {{result.league_name}}</p>
             <p>Number of Team : {{result.number_of_team}}</p>
              <p>League Type: {{result.league_type}}</p>
               <p>Game Type : {{result.game_type}}</p>
                 <p>Match Type : {{result.match_type}}</p>
                <a href="{{url_for('fast.EditLeague')}}" class="btn btn-lg btn-success"   >Edit</a>

          </div>
          </div>
         </div>
         {% endif %}

{% else %}
<div class="container">
        <div class="jumbotron">

         <div class="row">
           <div class="col-lg-2 col-md-2 col-sm-12">
           </div>
           <div class="col-lg-6 col-md-6 col-sm-12">
             <h1>Fantansy Game</h1>
           <a class="btn btn-success btn-lg" href="{{url_for('fast.CreateLeague')}}">Create League</a>

           <button class="btn btn-success btn-lg">Join League</button>
         </div>
           <div class="col-lg-2 col-md-2 col-sm-12">
           </div>
         </div>
         <div>

          </div>

        </div>






</div>




{% endif %}

{% endblock %}

app/templates/fast/league-info.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<div class="container well">
  <legend>League Info</legend>
  
  <div class="row">

    <div class="col-lg-4 col-md-4 col-sm-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">

  <img class="img-rounded" alt="Cinque Terre" width="304" height="236"
 src="{{result.url}}"></img>
 </div>
 <div "col-lg-4 col-md-4 col-sm-12">
   <p>Leage Name : {{result.league_name}}</p>
    <p>Number of Team : {{result.number_of_team}}</p>
     <p>League Type: {{result.league_type}}</p>
      <p>Game Type : {{result.game_type}}</p>
        <p>Match Type : {{result.match_type}}</p>
       <a href="{{url_for('fast.EditLeague')}}" class="btn btn-lg btn-success"   >Edit</a>

 </div>
 </div>
</div>

{% endblock %}

app/templates/fast/league.html
{% extends "base.html" %}
{% block page_content %}
<div class="space">
<h1>The page is under construction</h1>
</div>
{% endblock %}

app/templates/fast/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<div class="row">
  <div class="col-lg-2 col-md-2 col-sm-12">
  </div>
  <div class="col-lg-8 col-md-8 col-sm-12">
    <div class="panel panel-default">
    <div class="panel-heading">
      Edit Profile
    </div>
    <div class="panel-body">
    {{ wtf.quick_form(form) }}
    </div>
  </div>
  </div>
  <div class="col-lg-2 col-md-2 col-sm-12">
  </div>
</div>

  {% endblock %}

app/templates/fast/results.html
{% extends "base.html" %}
{% block page_content %}
<div class="space">
<h1>The page is under construction</h1>
</div>
{% endblock %}

app/templates/fast/team.html
{% extends "base.html" %}
{% block page_content %}
<div class="space">
<h1>The page is under construction</h1>
</div>
{% endblock %}

app/templates/fast/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header user-profile">
    <div class="user-avatar"><img src="{{current_user.avatar(128)}}"></div>
    {% if current_user == user %}<a class="btn btn-default pull-right" href="{{ url_for('fast.profile') }}">Edit Profile</a>{% endif %}
    <h1>{{ user.username }}</h1>
    <p>
       Name: {% if personal.first_name %}{{ personal.first_name }}{% endif %}{% if personal.last_name %} {{ personal.last_name }}<br>{% endif %}
       Address: {% if personal.location %}<a href="http://maps.google.com?q={{ personal.location }}">{{ personal.location }}</a><br>{% endif %}
    </p>

</div>

{% endblock %}